include:
  - compose.yml

services:
  frontend-tests:
    image: rubricapp-frontend
    pull_policy: never
    extends:
      file: compose.yml
      service: frontend
    # See FrontEndReact/jest-timeout-hack.js for the rationale behind the --setupFiles ./jest-timeout-hack.js hack
    # The ./node_modules/react-app-polyfill/jsdom.js setup file is enabled by default, but
    #  using any setupFiles args overrides the defaults so I have to add it
    #  manually
    entrypoint: npm test -- --cacheDirectory /tmp/jest-cache --setupFiles ./jest-timeout-hack.js --setupFiles ./node_modules/react-app-polyfill/jsdom.js
    command: []
    depends_on:
      - backend
    volumes:
      - "frontend-jest-cache:/tmp/jest-cache"
    ports: !override []
    environment:
      - REACT_APP_API_URL=http://backend:5000/api
  
  frontend-lint:
    image: rubricapp-frontend
    pull_policy: never
    extends:
      file: compose.yml
      service: frontend
    entrypoint: npx eslint .
    command: []
    depends_on: !override []
    ports: !override []
  
  backend-tests:
    image: rubricapp-backend
    pull_policy: never
    extends:
      file: compose.yml
      service: backend
    entrypoint: python setupEnv.py -t
    command: []
    depends_on: !override []
    ports: !override []

volumes:
  frontend-jest-cache:
