include:
  - compose.yml

services:
  frontend-tests:
    container_name: rubricapp-frontend-tests
    extends:
      file: compose.yml
      service: frontend
    entrypoint: npm test
    command: []
    volumes:
      - "frontend-jest-cache:/tmp"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:5000/api

volumes:
  frontend-jest-cache:
