include:
  - compose.yml

services:
  frontend-tests:
    extends:
      file: compose.yml
      service: frontend
    entrypoint: npm test -- --cacheDirectory /tmp/jest-cache
    command: []
    mem_limit: 3G
    depends_on:
      - backend
    volumes:
      - "frontend-jest-cache:/tmp/jest-cache"
    ports: !override []
    environment:
      - REACT_APP_API_URL=http://backend:5000/api
  
  frontend-lint:
    extends:
      file: compose.yml
      service: frontend
    entrypoint: npx eslint .
    command: []
    depends_on: !override []
    ports: !override []
  
  backend-tests:
    extends:
      file: compose.yml
      service: backend
    entrypoint: python setupEnv.py -t
    command: []
    depends_on: !override []
    ports: !override []

volumes:
  frontend-jest-cache:
