# Use a valid Node.js version as base
FROM node:20

# Set working directory
WORKDIR /app

# Copy only package files first to leverage Docker cache
COPY FrontEndReact/package*.json ./

# Disable Husky for docker
 ENV HUSKY=0

# Install dependencies (faster & deterministic)
RUN npm ci

# Copy the rest of the frontend code
COPY FrontEndReact/ ./

# Expose frontend port
EXPOSE 3000

# Start the frontend server
CMD ["npm", "start"]
