"""Added team_id to Feedback table

Revision ID: 043ce57b0be5
Revises: 496038258ecb
Create Date: 2025-07-15 22:43:33.447761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '043ce57b0be5'
down_revision = '496038258ecb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'Team', ['team_id'], ['team_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Feedback', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('team_id')

    # ### end Alembic commands ###