"""Added team_id field to Feedback table

Revision ID: 06d335bac0bb
Revises: 59e45eacc759
Create Date: 2025-07-09 21:01:51.649788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06d335bac0bb'
down_revision = '59e45eacc759'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('EmailValidation', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('EmailValidation_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'User', ['user_id'], ['user_id'])

    with op.batch_alter_table('Feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'Team', ['team_id'], ['team_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Feedback', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('team_id')

    with op.batch_alter_table('EmailValidation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('EmailValidation_ibfk_1'), 'User', ['user_id'], ['user_id'], ondelete='CASCADE')

    # ### end Alembic commands ###