"""Add assessment_task_id to Teams table

Revision ID: 2955b1b013eb
Revises: 59e45eacc759
Create Date: 2025-07-04 00:00:54.398011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2955b1b013eb'
down_revision = '59e45eacc759'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assessment_task_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'AssessmentTask', ['assessment_task_id'], ['assessment_task_id'])

    with op.batch_alter_table('UserCourse', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('UserCourse_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'User', ['user_id'], ['user_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('UserCourse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('UserCourse_ibfk_1'), 'User', ['user_id'], ['user_id'])

    with op.batch_alter_table('Team', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('assessment_task_id')

    with op.batch_alter_table('EmailValidation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('EmailValidation_ibfk_1'), 'User', ['user_id'], ['user_id'])

    # ### end Alembic commands ###
