"""Add cascade delete to EmailValidation.user_id

Revision ID: 496038258ecb
Revises: 59e45eacc759
Create Date: 2025-06-24 21:24:30.014681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '496038258ecb'
down_revision = '2955b1b013eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('EmailValidation', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('EmailValidation_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'User', ['user_id'], ['user_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('EmailValidation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('EmailValidation_ibfk_1'), 'User', ['user_id'], ['user_id'])

    # ### end Alembic commands ###