"""empty message

Revision ID: 62f6b9e34e01
Revises: 9aa494f95475
Create Date: 2025-10-16 16:05:40.377912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62f6b9e34e01'
down_revision = '9aa494f95475'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_dark_mode', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_column('user_dark_mode')

    # ### end Alembic commands ###
