"""User text fields to string with limits

Revision ID: 7c2e82728947
Revises: 9e451a7f31df
Create Date: 2025-10-01 20:17:00.685459

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7c2e82728947'
down_revision = '9e451a7f31df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('last_name',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=256),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('reset_code',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=6),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.alter_column('reset_code',
               existing_type=sa.String(length=6),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.String(length=20),
               type_=mysql.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.String(length=50),
               type_=mysql.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('first_name',
               existing_type=sa.String(length=50),
               type_=mysql.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###