#!/bin/sh
. "$(dirname "$0")"

# Check to see if there were changes to the drivers and udpate them.
if git diff --name-only HEAD@{1} HEAD | grep -qE 'Scripts/(setupMergeDriver.sh)$'; then
    echo "Changes to setupMergeDriver.sh found"
    sh ./Scripts/setupMergeDriver.sh
    echo "merge drivers updated"
else 
    echo "No changes to the merge drivers."
fi