name: Run Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build backend
        run: docker compose build backend
      
      - name: Start backend
        run: |
          docker compose up --no-build -d backend
          sleep 5
          curl -v 'http://127.0.0.1:5050/api'
      
      - name: Install Node dependencies
        run: |
          cd FrontEndReact
          npm install
      
      - name: Run Jest tests
        run: |
          cd FrontEndReact
          npm test
        env:
          REACT_APP_API_URL: 'http://127.0.0.1:5050/api'
